// Filesystem confinement.
//
// This is a security boundary and it had no tests. Its own header records the
// incident that created it — an agent told to write `outputs/SHIPPED.txt`
// created it two directories up and invented a phantom workspace on the way —
// so the cases below are the ones that must keep failing.
//
//   node --test tests/confine.test.ts

import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { checkPaths, checkBash } from "../packages/core/src/confine.ts";

const WORKSPACE = "/data/acme/workspaces/desk";
const ROOTS = {
  agentDir: `${WORKSPACE}/agents/writer`,
  workspaceRoot: WORKSPACE,
  libraryRoot: "/data/acme/library",
};

const write = (p: string) => checkPaths("Write", { file_path: p }, ROOTS);
const read = (p: string) => checkPaths("Read", { file_path: p }, ROOTS);

test("an agent may write inside its own workspace", () => {
  for (const p of [
    `${ROOTS.agentDir}/outputs/draft.md`,
    `${ROOTS.agentDir}/memory/what-i-learned.md`,
    `${WORKSPACE}/agents/checker/outputs/report.md`, // a teammate's output: same workspace
  ]) {
    assert.equal(write(p).ok, true, `${p} should be allowed`);
  }
});

test("escaping the workspace is denied", () => {
  for (const p of [
    "/etc/passwd",
    `${WORKSPACE}/../other-workspace/agents/x/agent.md`,
    `${WORKSPACE}/../../secrets.json`,
    `${ROOTS.agentDir}/../../../../SHIPPED.txt`, // the original incident
  ]) {
    const v = write(p);
    assert.equal(v.ok, false, `${p} must be denied`);
    assert.match(v.reason ?? "", /outside this workspace|protected platform file/);
  }
});

test("secrets are never a file an agent can read", () => {
  for (const p of [`${WORKSPACE}/secrets.json`, "/data/acme/library/secrets.json"]) {
    assert.equal(checkPaths("Read", { file_path: p }, ROOTS).ok, false, p);
  }
});

test("the run journal is read-only", () => {
  for (const p of [`${WORKSPACE}/runs/run-123.json`, `${WORKSPACE}/runs`]) {
    assert.equal(write(p).ok, false, p);
  }
});

test("a memory bundle's generated index and log are protected", () => {
  // Regenerated by syncBundleFor on every write, so an agent editing one is
  // writing something about to be overwritten — and until it is, the index
  // says whatever it was told to. memory/ is the case that matters: it is the
  // one bundle an agent may write to at all.
  for (const p of [
    `${WORKSPACE}/memory/index.md`,
    `${WORKSPACE}/memory/log.md`,
    `${ROOTS.agentDir}/memory/index.md`, // the agent's own bundle
    `${ROOTS.agentDir}/memory/archive/index.md`, // nested section
  ]) {
    const v = write(p);
    assert.equal(v.ok, false, `${p} must not be writable`);
    assert.match(v.reason ?? "", /generated from the files around it/);
  }
});

// Protected against editing, not against reading. A real run caught this: the
// agent was told to start from the index, asked for knowledge/index.md, was
// refused, and spent a turn recovering — from a generated, non-secret file
// that the whole progressive-disclosure design exists to have it read.
test("a generated index and log stay readable", () => {
  for (const p of [
    `${WORKSPACE}/memory/index.md`,
    `${WORKSPACE}/memory/log.md`,
    `${WORKSPACE}/knowledge/index.md`,
    `${ROOTS.agentDir}/memory/archive/index.md`,
  ]) {
    assert.equal(read(p).ok, true, `${p} must be readable`);
  }
});

// The journal is the one that stays denied both ways: a step that can read or
// rewrite its own history makes every other guarantee unverifiable.
test("the run journal is denied for reading as well as writing", () => {
  assert.equal(read(`${WORKSPACE}/runs/run-1.json`).ok, false);
  assert.equal(write(`${WORKSPACE}/runs/run-1.json`).ok, false);
});

test("knowledge/ is read-only to an agent, index or not", () => {
  // A separate and older rule: knowledge is given, memory is learned. Asserted
  // here because it is the reason the rule above only has to name memory.
  for (const p of [
    `${WORKSPACE}/knowledge/pricing.md`,
    `${WORKSPACE}/knowledge/index.md`,
    `${WORKSPACE}/knowledge/gauges/index.md`,
  ]) {
    const v = write(p);
    assert.equal(v.ok, false, `${p} must be denied`);
    assert.match(v.reason ?? "", /maintained by people|generated from the files/);
  }
  // Reading it is the whole point of it existing.
  assert.equal(checkPaths("Read", { file_path: `${WORKSPACE}/knowledge/pricing.md` }, ROOTS).ok, true);
});

test("an ordinary index.md is not collateral damage", () => {
  // The rule names knowledge/ and memory/ precisely so a deliverable called
  // index.md is still an ordinary file.
  for (const p of [
    `${ROOTS.agentDir}/outputs/index.md`,
    `${WORKSPACE}/outputs/site/index.md`,
    `${ROOTS.agentDir}/skills/writing/references/index.md`,
  ]) {
    assert.equal(write(p).ok, true, `${p} should be allowed`);
  }
});

test("a memory concept file is still writable", () => {
  // Memory is agent-writable by design; only the derived files are not.
  assert.equal(write(`${ROOTS.agentDir}/memory/house-tone.md`).ok, true);
});

test("bash that reaches outside the workspace is denied", () => {
  for (const cmd of [
    "cat /etc/passwd",
    "cd /",
    "cd ~",
    // `~` used to be guarded only for `cd`, so these two walked past the
    // second layer entirely — the obvious escapes it exists to name.
    "cat ~/.ssh/id_rsa",
    "cp ~/.aws/credentials .",
    "cat ../../../../../etc/hosts",
    "echo $ANTHROPIC_API_KEY",
  ]) {
    assert.equal(checkBash(cmd).ok, false, `${cmd} must be denied`);
  }
});

test("ordinary bash is allowed", () => {
  // `cd ../..` is the workspace root from an agent directory — ordinary work.
  for (const cmd of [
    "python3 scripts/pace.py --spent 10",
    "ls outputs/",
    "cd ../.. && ls",
    "echo done > outputs/x.txt",
  ]) {
    assert.equal(checkBash(cmd).ok, true, cmd);
  }
});

// The protections checkPaths applies to Write and Edit have to hold for Bash
// too, or `bash` in an agent's tools: is a way around them. It was: Write to
// knowledge/ was denied while `echo x > knowledge/prices.md` went through, and
// the run journal — the thing every other guarantee is verified against — could
// be rewritten by any agent granted a shell.
test("bash cannot write where the file tools may not", () => {
  for (const cmd of [
    "echo free > ../../knowledge/pricing.md",
    "echo x >> knowledge/p.md",
    "rm ../../knowledge/pricing.md",
    "sed -i s/400/0/ knowledge/p.md",
    "echo x | tee knowledge/p.md",
    "mv /tmp/x knowledge/p.md",
    // The journal is denied outright, reads included: a rule that differs by
    // tool is a rule an agent can shop around for.
    "echo x > ../../runs/r.json",
    "cat ../../runs/r.json",
    "echo x > memory/index.md",
  ]) {
    assert.equal(checkBash(cmd).ok, false, `${cmd} must be denied`);
  }
});

// The counterpart, and the reason knowledge/ is matched only alongside a
// writing shape: reading the price list is the whole point of having one, so a
// blanket rule would have banned `cat` to close a hole about `>`.
test("bash may still read knowledge and write everywhere it should", () => {
  for (const cmd of [
    "cat ../../knowledge/pricing.md",
    "grep -r surcharge knowledge/",
    "cat knowledge/p.md && echo done",
    "echo learned > memory/note.md",
    "echo draft > outputs/draft.md",
    "mkdir -p outputs/sub",
  ]) {
    assert.equal(checkBash(cmd).ok, true, cmd);
  }
});

// checkPaths lets an agent read a generated index; bash has to agree, or the
// rule differs by tool and the agent just uses the other one.
test("bash may read a generated index but not rewrite it", () => {
  for (const cmd of ["cat memory/index.md", "grep -n Fact knowledge/index.md", "head memory/log.md"]) {
    assert.equal(checkBash(cmd).ok, true, cmd);
  }
  for (const cmd of ["echo x > memory/index.md", "rm knowledge/index.md", "sed -i s/a/b/ memory/log.md"]) {
    assert.equal(checkBash(cmd).ok, false, cmd);
  }
});

// Both sides of the containment check must be resolved the same way, or the
// comparison is between two spellings of one place. On macOS `/var` is a
// symlink to `/private/var`: a workspace under the system temp directory was
// handed in as `/var/folders/…` while every path the agent produced came back
// as `/private/var/folders/…`, so it was told its own workspace was outside
// the workspace — on every write, for a whole run, while the run still
// reported success because the agent gave up politely.
test("a workspace reached through a symlink is still its own workspace", () => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "foldrun-link-"));
  try {
    const real = fs.realpathSync.native(root);
    const roots = {
      // As a caller supplies it: unresolved.
      agentDir: path.join(root, "agents/writer"),
      workspaceRoot: root,
      libraryRoot: path.join(root, "library"),
    };
    fs.mkdirSync(roots.agentDir, { recursive: true });

    // As the agent produces it: resolved.
    const target = path.join(real, "agents/writer/outputs/note.md");
    assert.notEqual(target.startsWith(root), target.startsWith(real) && root !== real);
    assert.equal(
      checkPaths("Write", { file_path: target }, roots).ok,
      true,
      "the resolved path was treated as outside the unresolved workspace",
    );

    // And the boundary still holds for something genuinely outside it.
    assert.equal(checkPaths("Write", { file_path: "/etc/passwd" }, roots).ok, false);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

// The other confinement layer. Scripts declared as tools are resolved and
// checked separately from the file tools, and it compared with a string
// prefix — so `<workspace>-attacker/steal.py` was inside `<workspace>`,
// because as text it is. Containment is a question about paths, and only
// path.relative answers it.
test("a sibling directory is not inside the workspace", () => {
  const root = fs.realpathSync.native(fs.mkdtempSync(path.join(os.tmpdir(), "foldrun-sib-")));
  try {
    const inside = path.join(root, "workspaces/desk");
    const sibling = path.join(root, "workspaces/desk-attacker");
    fs.mkdirSync(path.join(inside, "scripts"), { recursive: true });
    fs.mkdirSync(sibling, { recursive: true });
    fs.writeFileSync(path.join(inside, "scripts/ok.py"), "print(1)\n");
    fs.writeFileSync(path.join(sibling, "steal.py"), "print(2)\n");

    const within = (rootDir: string, candidate: string) => {
      const rel = path.relative(rootDir, candidate);
      return rel === "" || (!rel.startsWith("..") && !path.isAbsolute(rel));
    };

    assert.equal(within(inside, path.join(inside, "scripts/ok.py")), true);
    assert.equal(
      within(inside, path.join(sibling, "steal.py")),
      false,
      "a sibling whose name extends the workspace's is not in it",
    );
    // The shape that made the old check wrong.
    assert.equal(path.join(sibling, "steal.py").startsWith(inside), true);
  } finally {
    fs.rmSync(root, { recursive: true, force: true });
  }
});

// A secret env var is for *using*, not printing. The credential guard once
// matched any reference to $…TOKEN/KEY/SECRET/PASSWORD, which denied the
// entire point of secrets — ssh -i "$SSH_KEY", curl -H "…: $TOKEN". Now only
// a command that emits the value is blocked.
test("a command may use a secret env var, but not print it", () => {
  for (const cmd of [
    'ssh -i "$VM_SSH_KEY" -o StrictHostKeyChecking=accept-new mark@host hostname',
    'curl -H "Authorization: Bearer $API_TOKEN" https://api.example.com',
    "sshpass -e ssh mark@host uptime",
    'git clone https://x:$GIT_TOKEN@github.com/o/r',
  ]) {
    assert.equal(checkBash(cmd).ok, true, `${cmd} must be allowed`);
  }
  for (const cmd of [
    "echo $VM_SSH_KEY",
    'printf "%s" "$API_TOKEN"',
    "cat $SOME_SECRET",
  ]) {
    assert.equal(checkBash(cmd).ok, false, `${cmd} must be denied`);
  }
});

test("a grep pattern is a regex, not a location", () => {
  // Searching for the literal text "/dev/null" inside the workspace was
  // reported as escaping it — Grep says where to look with `path`, and that
  // argument is still checked.
  assert.equal(
    checkPaths("Grep", { pattern: "/dev/null", path: "." }, ROOTS).ok,
    true,
    "an absolute-looking regex is still a regex",
  );
  assert.equal(
    checkPaths("Grep", { pattern: "anything", path: "/etc/passwd" }, ROOTS).ok,
    false,
    "but the path argument is a path",
  );
  // Glob's pattern really is a path shape, so it keeps its check.
  assert.equal(checkPaths("Glob", { pattern: "/etc/*.conf" }, ROOTS).ok, false);
});
