// Filesystem confinement for an agent's own tools.
//
// Scripts already run in containers. The agent's *built-in* tools —
// Read/Write/Edit/Glob/Grep and friends — do not: they execute in the server
// process with its full permissions. A run proved this is not theoretical: an
// agent told to write `outputs/SHIPPED.txt` created it two directories up and
// invented a whole phantom workspace on the way.
//
// The boundary is the WORKSPACE, not the agent. Agents in one workspace are a
// team — a reviewer legitimately reads what the writer produced — while the
// workspace is the isolation unit for everything else in the platform, so it
// is the honest place to draw the line.
//
// Inside that boundary, three things are still off limits:
//   · secrets.json — the encrypted store; an agent gets secrets as env vars,
//     never as a file it can exfiltrate wholesale
//   · runs/ — the run journal is the audit trail, and a step that can rewrite
//     its own history makes every other guarantee unverifiable
//   · index.md and log.md inside a knowledge/ or memory/ bundle — generated by
//     the platform on every write. An agent scribbling on one would be undone
//     by the next syncBundleFor, but until then the index says whatever it was
//     told to say, and log.md is provenance for the same reason runs/ is.
//
// There is no curated index beside the generated one. A bundle has exactly the
// two reserved files OKF defines, and both are generated.
//
// The bundle scoping matters. An earlier draft denied any index.md anywhere,
// which would have blocked an agent writing outputs/index.md — a perfectly
// ordinary deliverable — so the rule names the two directories it applies to.

import path from "node:path";

/** Tool argument names that carry a filesystem path. */
const PATH_KEYS = [
  "file_path",
  "path",
  "notebook_path",
  "filePath",
  "edits", // NotebookEdit-style payloads are checked via file_path too
];

const DENIED_WITHIN = [
  /(^|\/)secrets\.json$/,
  /(^|\/)runs(\/|$)/,
];

/**
 * Generated, and therefore not an agent's to edit — but very much an agent's
 * to read.
 *
 * These were denied outright, and a run proved what that costs: an agent told
 * to start from the index asked for `knowledge/index.md`, was refused, and
 * spent a turn recovering. The index is the navigational artifact the whole
 * progressive-disclosure design rests on; refusing to let a reader open it is
 * the opposite of the intent. The reason they are protected is that a
 * generated file an agent can edit is one that can lie — which is an argument
 * about writing, and only about writing.
 */
const READ_ONLY_WITHIN = [/(^|\/)(knowledge|memory)\/(.*\/)?(index|log)\.md$/];

export interface ConfineVerdict {
  ok: boolean;
  reason?: string;
  /** Rewritten tool input, when a virtual prefix was expanded. */
  updatedInput?: Record<string, unknown>;
}

export interface Roots {
  /** The agent's own directory — relative paths resolve from here. */
  agentDir: string;
  /** The workspace: the read/write boundary. */
  workspaceRoot: string;
  /** The account library: readable, never writable. */
  libraryRoot: string;
}

// Skills are announced to the agent with virtual prefixes — `workspace/skills/…`
// for the workspace's, `library/skills/…` for the account's — because a skill
// at either scope lives outside the agent's own folder. Symlinking them in
// was tried and reverted: it recursed into the workspace's own file listing.
// Expanding the prefix here instead keeps one honest path per skill, with no
// duplication on disk.
// Two prefixes, named after the two scopes above an agent. There used to be
// three — `workspace/` meant the workspace root while `shared/` meant the
// workspace's *scripts*, which is exactly the kind of near-synonym that gets
// mis-typed. The old spellings still resolve so nothing existing breaks.
const VIRTUAL = [
  { prefix: "account/", root: (r: Roots) => r.libraryRoot, readOnly: true },
  { prefix: "workspace/", root: (r: Roots) => r.workspaceRoot, readOnly: false },
  // legacy, still accepted
  { prefix: "library/", root: (r: Roots) => r.libraryRoot, readOnly: true },
  { prefix: "workspace/", root: (r: Roots) => r.workspaceRoot, readOnly: false },
];

const WRITE_TOOLS = new Set(["Write", "Edit", "MultiEdit", "NotebookEdit"]);

// Only the built-in filesystem tools get path checks. mdagent's own MCP tools
// are already confined at their own layer — script paths by resolveRunPath,
// APIs by their declared base URL — and their arguments are not filesystem
// paths at all: `call_<api>` takes a *URL* path like "/uuid", which this
// check would otherwise reject as an escape.
const FS_TOOLS = new Set([
  "Read",
  "Write",
  "Edit",
  "MultiEdit",
  "NotebookEdit",
  "NotebookRead",
  "Glob",
  "Grep",
  "LS",
]);

export const isFilesystemTool = (toolName: string) => FS_TOOLS.has(toolName);

/** Expand a virtual prefix to a real absolute path, or null if it has none. */
export function expandVirtual(raw: string, roots: Roots): { abs: string; readOnly: boolean } | null {
  for (const v of VIRTUAL) {
    if (raw.startsWith(v.prefix)) {
      return { abs: path.resolve(v.root(roots), raw.slice(v.prefix.length)), readOnly: v.readOnly };
    }
  }
  return null;
}

export function checkPaths(
  toolName: string,
  input: Record<string, unknown>,
  roots: Roots,
): ConfineVerdict {
  const workspace = path.resolve(roots.workspaceRoot);
  const library = path.resolve(roots.libraryRoot);
  const isWrite = WRITE_TOOLS.has(toolName);
  let rewritten: Record<string, unknown> | undefined;

  const keys = [...PATH_KEYS, "glob", "pattern"];
  for (const key of keys) {
    const raw = input[key];
    if (typeof raw !== "string" || !raw.trim()) continue;
    // Glob/Grep patterns are only paths when they're anchored.
    if ((key === "glob" || key === "pattern") && !raw.startsWith("/") && !expandVirtual(raw, roots)) {
      continue;
    }

    const virtual = expandVirtual(raw, roots);
    const abs = virtual ? virtual.abs : path.resolve(roots.agentDir, raw);

    // Knowledge is given, not learned: an agent that rewrites the price list
    // it was handed has corrupted its own source of truth. What it discovers
    // goes to memory/, which it owns.
    if (isWrite && /(^|\/)knowledge\//.test(abs.split(path.sep).join("/"))) {
      return {
        ok: false,
        reason:
          `${toolName} was denied: knowledge/ is reference material maintained by people, not by ` +
          `you. If you learned something new, write it to memory/ instead.`,
      };
    }

    if (virtual?.readOnly && isWrite) {
      return {
        ok: false,
        reason:
          `${toolName} was denied: "${raw}" is in the shared library, which is read-only from a ` +
          `run. Change it in the dashboard under Shared, or write your own copy in this workspace.`,
      };
    }

    const inWorkspace = !path.relative(workspace, abs).startsWith("..");
    const inLibrary = !path.relative(library, abs).startsWith("..");
    if (!inWorkspace && !inLibrary) {
      return {
        ok: false,
        reason:
          `${toolName} was denied: "${raw}" is outside this workspace. Agents may only read and ` +
          `write inside their own workspace. Use a path relative to your agent directory.`,
      };
    }

    const within = path.relative(inLibrary ? library : workspace, abs).split(path.sep).join("/");
    if (DENIED_WITHIN.some((re) => re.test(within))) {
      return {
        ok: false,
        reason:
          `${toolName} was denied: "${raw}" is a protected platform file. Secrets reach you as ` +
          `environment variables, and the run journal is not yours to read or rewrite.`,
      };
    }

    if (isWrite && READ_ONLY_WITHIN.some((re) => re.test(within))) {
      return {
        ok: false,
        reason:
          `${toolName} was denied: "${raw}" is generated from the files around it and will be ` +
          `rewritten on the next write. Read it freely — to change what it says, change a ` +
          `concept file instead.`,
      };
    }

    // Hand the real path back to the tool, so the virtual prefix the prompt
    // advertises is one the agent can actually open.
    if (virtual) rewritten = { ...(rewritten ?? input), [key]: abs };
  }

  return { ok: true, updatedInput: rewritten };
}

// A shell can defeat any argument-level path check, so Bash is handled
// separately: it runs under the SDK sandbox, and these patterns are a second
// layer that catches the obvious escapes with a clear message rather than a
// confusing sandbox error.
const BASH_ESCAPES = [
  /\.\.\/\.\.\/\.\.\/\.\.\/\.\.\//, // five levels up leaves even the account
  /(^|[\s;|&(<>])cd\s+(\/|~)/, // cd to an absolute path or home
  // `~` was guarded only for `cd`, so `cat ~/.ssh/id_rsa` and
  // `cp ~/.aws/credentials .` walked straight past — the exact "obvious
  // escape" this layer exists to name before the sandbox does.
  /(^|[\s;|&(<>=:"'])~\//, // a home-relative path, whatever the command
  /(^|[\s;|&(<>])[a-z_]+\s+\/(etc|root|home|Users|var|proc|dev)\b/, // absolute system paths
  /secrets\.json/,
  /\.secret-key/,
  /\$\{?[A-Z_]*(TOKEN|KEY|SECRET|PASSWORD)/, // don't let a command echo a credential out
];

/**
 * Shapes that modify a file, as opposed to reading one.
 *
 * Bash cannot be checked the way a tool call can — there is no path argument,
 * only a string — so the protections checkPaths applies to Write and Edit have
 * to be recognised here from the command's shape. That is why `knowledge/` is
 * matched only alongside one of these: reading the price list is the entire
 * reason it exists, and a blanket rule would have banned `cat`.
 */
const WRITES_TO_A_FILE =
  /(>>?|\btee\b|\bsed\b[^]*?\s-i\b|\b(rm|mv|cp|truncate|dd|install|ln|chmod|chown|mkdir|rmdir|touch)\b)/;

/** Protections that mirror checkPaths, per command segment. */
const PROTECTED_BASH: { re: RegExp; writeOnly: boolean; reason: string }[] = [
  {
    re: /(^|[\s'"(/])knowledge\//,
    writeOnly: true,
    reason:
      "knowledge/ is reference material maintained by people, not by you. If you learned " +
      "something new, write it to memory/ instead.",
  },
  {
    // Not write-only: checkPaths denies reading the journal too, and a rule
    // that differs by tool is a rule an agent can shop around for.
    re: /(^|[\s'"(/])runs(\/|$)/,
    writeOnly: false,
    reason:
      "the run journal is the audit trail for this run, and is not yours to read or rewrite.",
  },
  {
    re: /(^|[\s'"(/])(knowledge|memory)\/(\S*\/)?(index|log)\.md/,
    // Write-only, matching checkPaths. A rule that differs by tool is a rule
    // an agent can shop around for — and reading the index is the point of it.
    writeOnly: true,
    reason:
      "index.md and log.md are generated from the files around them — write the concept file " +
      "instead.",
  },
];

export function checkBash(command: string): ConfineVerdict {
  for (const re of BASH_ESCAPES) {
    if (re.test(command)) {
      return {
        ok: false,
        reason:
          `Bash was denied: this command reaches outside the workspace. Work with paths relative ` +
          `to your agent directory.`,
      };
    }
  }

  // Per segment, so `cat knowledge/prices.md && echo done` is judged on the
  // part that touches the path rather than on the whole line.
  for (const segment of command.split(/[;|&]+|\n/)) {
    if (!segment.trim()) continue;
    const writes = WRITES_TO_A_FILE.test(segment);
    for (const rule of PROTECTED_BASH) {
      if (rule.writeOnly && !writes) continue;
      if (rule.re.test(segment)) return { ok: false, reason: `Bash was denied: ${rule.reason}` };
    }
  }
  return { ok: true };
}
